add_library(db_sources_files
        ../polar_api/accesslink.h
        db.cpp
        table_exercises.h
        table_exercises.cpp
        table_base.h
        table_base.cpp
        table_activity.h
        table_activity.cpp
        table_sleep.h
        table_sleep.cpp
        table_phys_info.h
        table_phys_info.cpp
)