add_library(polarapi_sources_files
        ../endpoints/daily_activity.cpp
        ../endpoints/daily_activity_transaction.cpp
        ../endpoints/physical_info.cpp
        ../endpoints/physical_info_transaction.cpp
        ../endpoints/pull_notifications.cpp
        ../endpoints/training_data.cpp
        ../endpoints/training_data_transaction.cpp
        ../endpoints/transaction.cpp
        ../endpoints/users.cpp
        ../accesslink.cpp
        ../oauth2.cpp
        ../request_wrap.cpp
)